# Generated by Django 5.2.4 on 2025-08-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0005_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='duyuru',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='duyurular/videos/', verbose_name='Duyuru Videosu'),
        ),
    ]
