# Generated by Django 5.2.4 on 2025-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0006_duyuru_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayasbilgi',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='ayas/videos/', verbose_name='Ayas Videosu'),
        ),
        migrations.AddField(
            model_name='etkinlik',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='etkinlikler/videos/', verbose_name='Etkinlik Videosu'),
        ),
        migrations.AddField(
            model_name='faydalibilgi',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='faydali_bilgiler/videos/', verbose_name='Faydalı Bilgi Videosu'),
        ),
    ]
