# Generated by Django 5.2.4 on 2025-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0007_ayasbilgi_video_etkinlik_video_faydalibilgi_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='DernekDokuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Döküman Başlığı')),
                ('aciklama', models.TextField(blank=True, verbose_name='Açıklama')),
                ('dosya', models.FileField(help_text='Sadece PDF dosyaları yükleyiniz', upload_to='dokumanlar/', verbose_name='PDF Dosyası')),
                ('yukleme_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yüklenme Tarihi')),
            ],
            options={
                'verbose_name': 'Dernek Dökümanı',
                'verbose_name_plural': 'Dernek Dökümanları',
            },
        ),
    ]
