# Generated by Django 5.2.4 on 2025-09-23 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0008_dernekdokuman'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DernekDokuman',
        ),
    ]
