# Generated by Django 5.2.4 on 2025-10-16 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0009_delete_dernekdokuman'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyasKoyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Köy Adı')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='ayas_koyleri/', verbose_name='Görsel')),
                ('video', models.FileField(blank=True, null=True, upload_to='ayas_koyleri/videos/', verbose_name='Video')),
                ('nufus', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nüfus')),
                ('uzaklik', models.CharField(blank=True, max_length=100, null=True, verbose_name='Merkeze Uzaklık')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Ayaş Köyü',
                'verbose_name_plural': 'Ayaş Köyleri',
                'ordering': ['sira', 'baslik'],
            },
        ),
        migrations.CreateModel(
            name='AyastanHaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Haber Başlığı')),
                ('aciklama', models.TextField(verbose_name='Haber İçeriği')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='ayas_haberler/', verbose_name='Haber Görseli')),
                ('video', models.FileField(blank=True, null=True, upload_to='ayas_haberler/videos/', verbose_name='Haber Videosu')),
                ('tarih', models.DateField(verbose_name='Haber Tarihi')),
                ('yayinlanma_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('aktif', models.BooleanField(default=True, help_text='Haberi göster/gizle', verbose_name='Aktif')),
            ],
            options={
                'verbose_name': "Ayaş'tan Haber",
                'verbose_name_plural': "Ayaş'tan Haberler",
                'ordering': ['-tarih', '-yayinlanma_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='AyasTarihi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='ayas_tarihi/', verbose_name='Görsel')),
                ('video', models.FileField(blank=True, null=True, upload_to='ayas_tarihi/videos/', verbose_name='Video')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Ayaş Tarihi',
                'verbose_name_plural': 'Ayaş Tarihi',
                'ordering': ['sira', '-tarih'],
            },
        ),
        migrations.CreateModel(
            name='DigerBilgi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='diger_bilgiler/', verbose_name='Görsel')),
                ('video', models.FileField(blank=True, null=True, upload_to='diger_bilgiler/videos/', verbose_name='Video')),
                ('kategori', models.CharField(blank=True, help_text='Örn: Kültür, Ekonomi, Ulaşım', max_length=100, null=True, verbose_name='Kategori')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Diğer Bilgi',
                'verbose_name_plural': 'Diğer Bilgiler',
                'ordering': ['sira', '-tarih'],
            },
        ),
        migrations.CreateModel(
            name='GezilecekYer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200, verbose_name='Başlık')),
                ('aciklama', models.TextField(verbose_name='Açıklama')),
                ('resim', models.ImageField(blank=True, null=True, upload_to='gezilecek_yerler/', verbose_name='Görsel')),
                ('video', models.FileField(blank=True, null=True, upload_to='gezilecek_yerler/videos/', verbose_name='Video')),
                ('konum', models.CharField(blank=True, help_text='Yer tarifi veya koordinat', max_length=200, null=True, verbose_name='Konum')),
                ('tarih', models.DateField(auto_now_add=True, verbose_name='Tarih')),
                ('sira', models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra')),
            ],
            options={
                'verbose_name': 'Gezilecek Yer',
                'verbose_name_plural': 'Gezilecek Yerler',
                'ordering': ['sira', '-tarih'],
            },
        ),
        migrations.AlterModelOptions(
            name='ayasbilgi',
            options={'verbose_name': 'Ayaş Bilgi', 'verbose_name_plural': 'Ayaş Bilgileri'},
        ),
        migrations.AlterModelOptions(
            name='duyuru',
            options={'verbose_name': 'Duyuru', 'verbose_name_plural': 'Duyurular'},
        ),
        migrations.AlterModelOptions(
            name='etkinlik',
            options={'verbose_name': 'Etkinlik', 'verbose_name_plural': 'Etkinlikler'},
        ),
        migrations.AlterModelOptions(
            name='faydalibilgi',
            options={'verbose_name': 'Faydalı Bilgi', 'verbose_name_plural': 'Faydalı Bilgiler'},
        ),
    ]
