# Generated by Django 5.2.4 on 2025-10-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0010_ayaskoyu_ayastanhaber_ayastarihi_digerbilgi_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.DeleteModel(
            name='Duyuru',
        ),
        migrations.DeleteModel(
            name='Etkinlik',
        ),
        migrations.DeleteModel(
            name='FaydaliBilgi',
        ),
    ]
