# Generated by Django 5.2.4 on 2025-11-01 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0011_delete_contactmessage_delete_duyuru_delete_etkinlik_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayastarihi',
            options={'ordering': ['kategori', 'sira', '-tarih'], 'verbose_name': 'Ayaş Tarihi', 'verbose_name_plural': 'Ayaş Tarihi'},
        ),
        migrations.AddField(
            model_name='ayastarihi',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Genel Ayaş Tarihi'), ('sahsiyetler', 'İz Bırakan Şahsiyetler'), ('hikayeler', 'Hikayeler'), ('gelenekler', 'Gelenekler')], default='genel', help_text='İçeriğin ait olduğu kategori', max_length=20, verbose_name='Kategori'),
        ),
    ]
