# Generated by Django 5.2.4 on 2025-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0012_alter_ayastarihi_options_ayastarihi_kategori'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='digerbilgi',
            options={'ordering': ['kategori', 'sira', '-tarih'], 'verbose_name': 'Diğer Bilgi', 'verbose_name_plural': 'Diğer Bilgiler'},
        ),
        migrations.AlterField(
            model_name='digerbilgi',
            name='kategori',
            field=models.CharField(choices=[('yemek', 'Ayaşa ait Yemek Tarifleri'), ('dergi', 'Ayaş Dergileri')], default='yemek', help_text='İçeriğin ait olduğu kategori', max_length=20, verbose_name='Kategori'),
        ),
    ]
