# Generated by Django 5.2.4 on 2025-11-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0013_alter_digerbilgi_options_alter_digerbilgi_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='digerbilgi',
            name='pdf_dosya',
            field=models.FileField(blank=True, help_text='Dergi için PDF dosyası (sadece Ayaş Dergileri kategorisi için)', null=True, upload_to='diger_bilgiler/pdf/', verbose_name='PDF Dosyası'),
        ),
    ]
