# Generated by Django 5.2.4 on 2025-11-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0014_digerbilgi_pdf_dosya'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ayastanhaber',
            options={'ordering': ['kategori', 'sira', '-tarih', '-yayinlanma_tarihi'], 'verbose_name': "Ayaş'tan Haber", 'verbose_name_plural': "Ayaş'tan Haberler"},
        ),
        migrations.AddField(
            model_name='ayastanhaber',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Genel'), ('mulakat', 'Ayaşlılar ile Mülakat'), ('gezelim', 'Gezelim Görelim Faaliyetleri'), ('siir', 'Şiirler'), ('fotograf', 'Fotoğraflar')], default='genel', help_text='Haberin ait olduğu kategori', max_length=20, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='ayastanhaber',
            name='sira',
            field=models.IntegerField(default=0, help_text='Gösterim sırası (küçükten büyüğe)', verbose_name='Sıra'),
        ),
    ]
