# Generated by Django 5.2.4 on 2025-11-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anasayfa', '0015_alter_ayastanhaber_options_ayastanhaber_kategori_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayastanhaber',
            name='kategori',
            field=models.CharField(choices=[('genel', 'Genel'), ('mulakat', 'Ayaşlılar ile Mülakat'), ('gezelim', 'Gezelim Görelim Faaliyetleri'), ('siir', 'Şiirler'), ('yazi', 'Yazılar'), ('fotograf', 'Fotoğraflar')], default='genel', help_text='Haberin ait olduğu kategori', max_length=20, verbose_name='Kategori'),
        ),
    ]
